version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_custom
    restart: always
    environment:
      POSTGRES_USER: usr_clayton
      POSTGRES_PASSWORD: Tlps1127*/
      POSTGRES_DB: db_petalflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
